version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: nuget restore Guardians.Library.sln
  - cmd: dotnet restore
build_script:
  # output will be in ./src/bin/debug/netcoreapp1.1/publish
  - cmd: MSBuild Guardians.Library.sln /property:Configuration=Release
after_build:
  # For once the build has completed
artifacts:
  # None right now
clone_depth: 1
test_script:
  # restore packages for our unit tests
  - cmd: dotnet restore Guardians.Library.sln
  # run the unit tests (requires changing into the test directory)
  - cmd: cd test
  - cmd: dotnet test Guardians.Models.Tests/Guardians.Models.Tests.csproj
on_finish :
  # any cleanup in here
deploy: off